### ISSUE TITLE
最新版本UI似乎回退了

### ISSUE THREAD

**Issue by RoyRao2333** [zhile-io/pandora-cloud#4]
如图，之前0.6.1的对话在hover的时候会有背景框，现在0.7.2似乎UI回退到老版本了。还是希望能够将新的UI放回来，个人很喜欢。谢谢！

<img width="1532" alt="image" src="https://github.com/zhile-io/pandora-cloud/assets/31413093/4502ceff-05dd-4f03-8a39-fd03eedecc03">

**Comment by zhile-io** [comment]
官方不知因为什么关闭了新ui
